# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.provider "hyperv"
  config.vm.network "Default Switch"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = true
    h.linked_clone = true
  end
end
 #  config.vm.provision "shell", inline: <<-SHELL
 #     sudo git clone https://github.com/mimura1133/linux-vm-tools /opt/linux-vm-tools
 #     sudo chmod 0755 /opt/linux-vm-tools/kali/2020.x/install.sh
  #    sudo /opt/linux-vm-tools/kali/2020.x/install.sh
  #    sudo reboot -f
  #   apt-get install -y apache2
  # SHELL
#end
